### ISSUE TITLE
Elementor Pro

### ISSUE THREAD

**Issue by floscholl** [sharafdin/nulled-elementor-pro#10]
Good morning,
The problem is that the theme builder template doesn't work, and I created header and footer templates with the old one and it no longer works.
can you give me some tips
Thanks in advance
Florence
<img width="1264" alt="Capture d’écran" src="https://github.com/user-attachments/assets/49a783d2-4356-4b05-b7ff-011a8b3d71fd">

**Comment by sharafdin** [comment]
> Good morning, The problem is that the theme builder template doesn't work, and I created header and footer templates with the old one and it no longer works. can you give me some tips Thanks in advance Florence <img alt="Capture d’écran" width="1264" src="https://private-user-images.githubusercontent.com/53981329/382274859-49a783d2-4356-4b05-b7ff-011a8b3d71fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTI3NjUsIm5iZiI6MTczMDU1MjQ2NSwicGF0aCI6Ii81Mzk4MTMyOS8zODIyNzQ4NTktNDlhNzgzZDItNDM1Ni00YjA1LWI3ZmYtMDExYThiM2Q3MWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEzMDEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZGZkZmRkNGZkZjE4YTJmN2ExNmZhNDBjYzIyOWZjNTYyNzYyZTM4OWFjZTQzYTMwZGI1ZTFlODQ5ZWFjYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n6I6gzJaX4E7XRv7xt1uzS0tqDlKF0qAU_6T0i7SGqs">

Good morning Florence,

It sounds like the issue might be due to compatibility changes with the new version of the theme builder. Here are some steps you can try to resolve it:

1. **Check Compatibility**: Sometimes, updates in theme builders affect older templates. Make sure the current version supports templates created in the older version.

2. **Recreate Templates**: Try recreating the header and footer templates from scratch within the updated theme builder. This may resolve any compatibility issues introduced by the update.

3. **Clear Cache**: If your CMS has a caching system, clear it. Cached versions of your site might be preventing new changes from taking effect.

4. **Theme Builder Settings**: Double-check the theme builder settings to ensure your new header and footer templates are correctly assigned.

5. **Check Error Logs**: If you have access to error logs, take a look to see if there are any clues about why the templates aren’t working.

Let me know if you need further assistance!
