### ISSUE TITLE
Exceeds max filesize

### ISSUE THREAD

**Issue by Schmimimi** [sharafdin/nulled-elementor-pro#6]
Following error message appeared when uploading the zip: "The uploaded file exceeds the upload_max_filesize directive in php.ini."

**Comment by sharafdin** [comment]
> Following error message appeared when uploading the zip: "The uploaded file exceeds the upload_max_filesize directive in php.ini."

Hi **Schmimimi**, it looks like the issue is related to the server's `upload_max_filesize` directive in `php.ini`. Here's how you can fix it:

1. Open your `php.ini` file on your server. You can typically find it in one of these locations:
   - `/etc/php/7.x/apache2/php.ini` (for Apache)
   - `/etc/php/7.x/cli/php.ini`
   - `/usr/local/lib/php.ini`
   (The location depends on your PHP version and server configuration.)

2. Look for the following lines in the `php.ini` file:
   ```ini
   upload_max_filesize = 2M
   post_max_size = 8M

3. Increase the values as needed, for example:
   ```ini
   upload_max_filesize = 500M
   post_max_size = 500M

4. After saving the changes, restart your web server to apply the new configuration:
 - For Apache: `sudo service apache2 restart`
- For Nginx (if using PHP-FPM): `sudo service php7.x-fpm restart and sudo service nginx restart`

This should resolve the issue. If you need further assistance, let me know!

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ilsondev** [comment]
Hiho @Schmimimi 
How are you?
You can do like @sharafdin suggested.
Or you can search for this plugin: 
https://wordpress.org/plugins/upload-max-file-size/

Kind regards,
Ilson Nóbrega
